version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      VITE_API_URL: http://0.0.0.0:8080
    restart: unless-stopped
